### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 14041980ClaytonChenxiLiew** [SanjaySunil/BetterDiscordPanel#36] opened 2021-04-07 13:50 UTC
#### How major is the bug from 1 - 10
- Scale: 7

#### What type of bug is it?
- Type: Send Msg Button does not respond and Pictures are not loading properly

#### Steps required to reproduce the bug
- Steps: Evaluate and Check the error on the bug with regards to the buttons and icons not loading properly as they should be

**Comment by SanjaySunil** [comment] 2021-04-07 14:10
Please provide a screenshot of evidence as I cannot reproduce this issue.

**Comment by 14041980ClaytonChenxiLiew** [comment] 2021-04-07 14:44
Hey there 
Thank your for getting back to me Sanjay Sorry for not attaching pics of errors and I forgot to dictate in the Bug Issue that my chat bots have an error loading i have no clue why though. Could it be a hardware issue or a software issue! I have now attached some screenshots

![Screenshot (426)](https://user-images.githubusercontent.com/72314373/113885952-2f672e80-97b8-11eb-9b99-74ac8d4e1940.png)
![Screenshot (427)](https://user-images.githubusercontent.com/72314373/113885965-3130f200-97b8-11eb-9880-4636f5ea3170.png)

**Comment by SanjaySunil** [comment] 2021-04-07 16:07
Hi,

First of all, you haven't selected a guild. That's why there is no picture there. I'm assuming that your bot isn't in any servers, otherwise it will automatically open on one.

You can't send any messages because you haven't selected a guild and channel.

The translations as well have loaded. There is currently only an English translation for the actual panel. The control panel (BetterDiscordPanel.cmd) only has translations. Translation support and guides are coming soon on later updates.

These problems aren't with the app, therefore I'm closing this issue here. 

More support is available at the BetterDiscordPanel discord support server.

**Closed** 2021-04-07 16:10 UTC
