### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Aspect0002** [SanjaySunil/BetterDiscordPanel#96] opened 2021-11-13 11:37 UTC
#### How major is the bug from 1 - 10
- Scale: 10

#### What type of bug is it?
- Type: INVALID TOKEN

#### Steps required to reproduce the bug
- Steps: ENTER TOKEN

**Comment by sarptekbas** [comment] 2021-11-13 19:46
Duplicate of #94. Caused by a CORS policy change made by Discord.

**Closed** 2021-11-14 10:09 UTC
Labels: duplicate
