### ISSUE TITLE
[BUG] news channels not appearing in chat

### ISSUE THREAD

**Issue by mchangrh** [SanjaySunil/BetterDiscordPanel#46] opened 2021-05-11 20:29 UTC
#### How major is the bug from 1 - 10
- Scale: 6

#### What type of bug is it?
- Type: Lack of Functionality

#### Steps required to reproduce the bug
- Create a "announcement/ news" channel
- Try to view channel on panel

#### Screenshot (In most cases required)
- Screenshot:
![image](https://user-images.githubusercontent.com/15132783/117880215-daff1500-b275-11eb-8820-4bc59f55b099.png)
![image](https://user-images.githubusercontent.com/15132783/117880256-e8b49a80-b275-11eb-8515-ca5cedcb0674.png)
![image](https://user-images.githubusercontent.com/15132783/117880288-f1a56c00-b275-11eb-8457-57248baeccf7.png)

**Comment by SanjaySunil** [comment] 2021-12-19 19:04
Duplicate of https://github.com/SanjaySunil/BetterDiscordPanel/issues/59

**Closed by SanjaySunil** 2021-12-19 19:04 UTC
Labels: bug
